api_key: API_KEY_HERE
admin_id: 42
mqtt:
    url: wss://HOST:PORT
    username: USERNAME
    password: PASSWORD
authorized_users: []
registration:
    - name: kitchen
      topic: livingroom/light_kitchen
      values:
        - "on"
        - "off"
    - name: bathroom
      topic: bathroom/force_light
      values:
        - none
        - big
        - small
        - "off"
    - name: pc
      topic: livingroom/light_pc
      values:
        - "on"
        - "off"
    - name: workbench
      topic: livingroom/light_bench
      values:
        - "on"
        - "off"
    - name: box
      topic: livingroom/light_box
      values:
        - "on"
        - "off"
    - name: amp
      topic: livingroom/light_amp
      values:
        - "on"
        - "off"
    - name: solderlights
      topic: livingroom/workbench/cmnd/POWER
      values:
        - "on"
        - "off"
    - name: audioout
      topic: livingroom/amp/cmnd/POWER
      values:
        - "on"
        - "off"
    - name: cornerlight
      topic: livingroom/light_corner/cmnd/POWER
      values:
        - "on"
        - "off"
    - name: sink
      topic: livingroom/light_sink/cmnd/POWER
      values:
        - "on"
        - "off"
    - name: fan
      topic: bathroom/force_fan
      values:
        - "360"
        - "120"
        - "60"
        - "30"
        - "10"
        - "0"
